// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nSWRgpKu4qTJd_XjqHHsLTYpxsAIg1I',
    appId: '1:383426424190:android:8b25e40e5d51d47d3b972f',
    messagingSenderId: '383426424190',
    projectId: 'thewall-f61fc',
    storageBucket: 'thewall-f61fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTQ_9ymlS_Lk2PNuhFCf_eskGzfqWkqM',
    appId: '1:383426424190:ios:4001f4c2fda9cd663b972f',
    messagingSenderId: '383426424190',
    projectId: 'thewall-f61fc',
    storageBucket: 'thewall-f61fc.appspot.com',
    iosBundleId: 'com.example.thewall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTQ_9ymlS_Lk2PNuhFCf_eskGzfqWkqM',
    appId: '1:383426424190:ios:4001f4c2fda9cd663b972f',
    messagingSenderId: '383426424190',
    projectId: 'thewall-f61fc',
    storageBucket: 'thewall-f61fc.appspot.com',
    iosBundleId: 'com.example.thewall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Kj-nbwKemM5YkXUjvzQtQANlYNsDhCo',
    appId: '1:383426424190:web:a4072c5565573c023b972f',
    messagingSenderId: '383426424190',
    projectId: 'thewall-f61fc',
    authDomain: 'thewall-f61fc.firebaseapp.com',
    storageBucket: 'thewall-f61fc.appspot.com',
  );
}
